// Plan de comptes — nomenclature PCG (version antérieure au règlement ANC 2022-06), libellés français.
// Maquette : extrait représentatif (toutes les classes, sous-comptes courants). Le plan complet arrive avec l'application.
window.PCG = window.PCG || {};
PCG.classes = [
  { n: "1", t: "Comptes de capitaux", s: "Capital, réserves, résultat, subventions d'investissement, provisions, emprunts" },
  { n: "2", t: "Comptes d'immobilisations", s: "Incorporelles, corporelles, financières, amortissements et dépréciations" },
  { n: "3", t: "Stocks et en-cours", s: "Matières, approvisionnements, en-cours, produits, marchandises" },
  { n: "4", t: "Comptes de tiers", s: "Fournisseurs, clients, personnel, organismes sociaux, État, associés" },
  { n: "5", t: "Comptes financiers", s: "Valeurs mobilières, banques, caisse, virements internes" },
  { n: "6", t: "Comptes de charges", s: "Achats, services extérieurs, impôts, personnel, financier, exceptionnel, dotations" },
  { n: "7", t: "Comptes de produits", s: "Ventes, production, subventions, financier, exceptionnel, reprises" },
  { n: "8", t: "Comptes spéciaux", s: "Engagements hors bilan, résultat en instance d'affectation, bilan" }
];
PCG.accounts = [
  // ---------- Classe 1 ----------
  ["10", "Capital et réserves"],
  ["101", "Capital"],
  ["1011", "Capital souscrit - non appelé"],
  ["1012", "Capital souscrit - appelé, non versé"],
  ["1013", "Capital souscrit - appelé, versé"],
  ["1018", "Capital souscrit soumis à des réglementations particulières"],
  ["104", "Primes liées au capital social"],
  ["1041", "Primes d'émission"],
  ["1042", "Primes de fusion"],
  ["1043", "Primes d'apport"],
  ["1044", "Primes de conversion d'obligations en actions"],
  ["1045", "Bons de souscription d'actions"],
  ["105", "Écarts de réévaluation"],
  ["1051", "Réserve spéciale de réévaluation"],
  ["1052", "Écart de réévaluation libre"],
  ["1053", "Réserve de réévaluation"],
  ["1055", "Écart de réévaluation (autres opérations légales)"],
  ["106", "Réserves"],
  ["1061", "Réserve légale"],
  ["1062", "Réserves indisponibles"],
  ["1063", "Réserves statutaires ou contractuelles"],
  ["1064", "Réserves réglementées"],
  ["1068", "Autres réserves"],
  ["107", "Écart d'équivalence"],
  ["108", "Compte de l'exploitant"],
  ["109", "Actionnaires : capital souscrit - non appelé"],
  ["11", "Report à nouveau (solde créditeur ou débiteur)"],
  ["110", "Report à nouveau (solde créditeur)"],
  ["119", "Report à nouveau (solde débiteur)"],
  ["12", "Résultat de l'exercice (bénéfice ou perte)"],
  ["120", "Résultat de l'exercice (bénéfice)"],
  ["129", "Résultat de l'exercice (perte)"],
  ["13", "Subventions d'investissement"],
  ["131", "Subventions d'équipement"],
  ["1311", "État"],
  ["1312", "Régions"],
  ["1313", "Départements"],
  ["1314", "Communes"],
  ["1315", "Collectivités publiques"],
  ["1316", "Entreprises publiques"],
  ["1317", "Entreprises et organismes privés"],
  ["1318", "Autres"],
  ["138", "Autres subventions d'investissement"],
  ["139", "Subventions d'investissement inscrites au compte de résultat"],
  ["1391", "Subventions d'équipement"],
  ["1398", "Autres subventions d'investissement"],
  ["14", "Provisions réglementées"],
  ["142", "Provisions réglementées relatives aux immobilisations"],
  ["143", "Provisions réglementées relatives aux stocks"],
  ["144", "Provisions réglementées relatives aux autres éléments de l'actif"],
  ["145", "Amortissements dérogatoires"],
  ["146", "Provision spéciale de réévaluation"],
  ["147", "Plus-values réinvesties"],
  ["148", "Autres provisions réglementées"],
  ["15", "Provisions"],
  ["151", "Provisions pour risques"],
  ["1511", "Provisions pour litiges"],
  ["1512", "Provisions pour garanties données aux clients"],
  ["1513", "Provisions pour pertes sur marchés à terme"],
  ["1514", "Provisions pour amendes et pénalités"],
  ["1515", "Provisions pour pertes de change"],
  ["1516", "Provisions pour pertes sur contrats"],
  ["1518", "Autres provisions pour risques"],
  ["153", "Provisions pour pensions et obligations similaires"],
  ["154", "Provisions pour restructurations"],
  ["155", "Provisions pour impôts"],
  ["156", "Provisions pour renouvellement des immobilisations (entreprises concessionnaires)"],
  ["157", "Provisions pour charges à répartir sur plusieurs exercices"],
  ["1572", "Provisions pour gros entretien ou grandes révisions"],
  ["158", "Autres provisions pour charges"],
  ["1581", "Provisions pour remises en état"],
  ["16", "Emprunts et dettes assimilées"],
  ["161", "Emprunts obligataires convertibles"],
  ["163", "Autres emprunts obligataires"],
  ["164", "Emprunts auprès des établissements de crédit"],
  ["165", "Dépôts et cautionnements reçus"],
  ["1651", "Dépôts"],
  ["1655", "Cautionnements"],
  ["166", "Participation des salariés aux résultats"],
  ["1661", "Comptes bloqués"],
  ["1662", "Fonds de participation"],
  ["167", "Emprunts et dettes assortis de conditions particulières"],
  ["1671", "Émissions de titres participatifs"],
  ["1674", "Avances conditionnées de l'État"],
  ["1675", "Emprunts participatifs"],
  ["168", "Autres emprunts et dettes assimilées"],
  ["1681", "Autres emprunts"],
  ["1685", "Rentes viagères capitalisées"],
  ["1687", "Autres dettes"],
  ["1688", "Intérêts courus"],
  ["169", "Primes de remboursement des obligations"],
  ["17", "Dettes rattachées à des participations"],
  ["171", "Dettes rattachées à des participations (groupe)"],
  ["174", "Dettes rattachées à des participations (hors groupe)"],
  ["178", "Dettes rattachées à des sociétés en participation"],
  ["18", "Comptes de liaison des établissements et sociétés en participation"],
  ["181", "Comptes de liaison des établissements"],
  ["186", "Biens et prestations de services échangés entre établissements (charges)"],
  ["187", "Biens et prestations de services échangés entre établissements (produits)"],
  ["188", "Comptes de liaison des sociétés en participation"],
  // ---------- Classe 2 ----------
  ["20", "Immobilisations incorporelles"],
  ["201", "Frais d'établissement"],
  ["2011", "Frais de constitution"],
  ["2012", "Frais de premier établissement"],
  ["2013", "Frais d'augmentation de capital et d'opérations diverses (fusions, scissions, transformations)"],
  ["203", "Frais de recherche et de développement"],
  ["205", "Concessions et droits similaires, brevets, licences, marques, procédés, logiciels, droits et valeurs similaires"],
  ["206", "Droit au bail"],
  ["207", "Fonds commercial"],
  ["208", "Autres immobilisations incorporelles"],
  ["2081", "Mali de fusion sur actifs incorporels"],
  ["21", "Immobilisations corporelles"],
  ["211", "Terrains"],
  ["2111", "Terrains nus"],
  ["2112", "Terrains aménagés"],
  ["2113", "Sous-sols et sur-sols"],
  ["2114", "Terrains de gisement"],
  ["2115", "Terrains bâtis"],
  ["212", "Agencements et aménagements de terrains"],
  ["213", "Constructions"],
  ["2131", "Bâtiments"],
  ["2135", "Installations générales, agencements, aménagements des constructions"],
  ["2138", "Ouvrages d'infrastructure"],
  ["214", "Constructions sur sol d'autrui"],
  ["2141", "Bâtiments sur sol d'autrui"],
  ["2145", "Installations générales, agencements, aménagements des constructions sur sol d'autrui"],
  ["2148", "Ouvrages d'infrastructure sur sol d'autrui"],
  ["215", "Installations techniques, matériel et outillage industriels"],
  ["2151", "Installations complexes spécialisées"],
  ["2153", "Installations à caractère spécifique"],
  ["2154", "Matériel industriel"],
  ["2155", "Outillage industriel"],
  ["2157", "Agencements et aménagements du matériel et outillage industriels"],
  ["218", "Autres immobilisations corporelles"],
  ["2181", "Installations générales, agencements, aménagements divers"],
  ["2182", "Matériel de transport"],
  ["2183", "Matériel de bureau et matériel informatique"],
  ["2184", "Mobilier"],
  ["2185", "Cheptel"],
  ["2186", "Emballages récupérables"],
  ["2187", "Mali de fusion sur actifs corporels"],
  ["22", "Immobilisations mises en concession"],
  ["23", "Immobilisations en cours"],
  ["231", "Immobilisations corporelles en cours"],
  ["2312", "Terrains"],
  ["2313", "Constructions"],
  ["2315", "Installations techniques, matériel et outillage industriels"],
  ["2318", "Autres immobilisations corporelles"],
  ["232", "Immobilisations incorporelles en cours"],
  ["237", "Avances et acomptes versés sur immobilisations incorporelles"],
  ["238", "Avances et acomptes versés sur commandes d'immobilisations corporelles"],
  ["26", "Participations et créances rattachées à des participations"],
  ["261", "Titres de participation"],
  ["2611", "Actions"],
  ["2618", "Autres titres"],
  ["266", "Autres formes de participation"],
  ["267", "Créances rattachées à des participations"],
  ["2671", "Créances rattachées à des participations (groupe)"],
  ["2674", "Créances rattachées à des participations (hors groupe)"],
  ["2675", "Versements représentatifs d'apports non capitalisés (appel de fonds)"],
  ["2676", "Avances consolidables"],
  ["2677", "Autres créances rattachées à des participations"],
  ["2678", "Intérêts courus"],
  ["268", "Créances rattachées à des sociétés en participation"],
  ["269", "Versements restant à effectuer sur titres de participation non libérés"],
  ["27", "Autres immobilisations financières"],
  ["271", "Titres immobilisés autres que les titres immobilisés de l'activité de portefeuille (droit de propriété)"],
  ["2711", "Actions"],
  ["2718", "Autres titres"],
  ["272", "Titres immobilisés (droit de créance)"],
  ["2721", "Obligations"],
  ["2722", "Bons"],
  ["273", "Titres immobilisés de l'activité de portefeuille"],
  ["274", "Prêts"],
  ["2741", "Prêts participatifs"],
  ["2742", "Prêts aux associés"],
  ["2743", "Prêts au personnel"],
  ["2748", "Autres prêts"],
  ["275", "Dépôts et cautionnements versés"],
  ["2751", "Dépôts"],
  ["2755", "Cautionnements"],
  ["276", "Autres créances immobilisées"],
  ["2761", "Créances diverses"],
  ["2768", "Intérêts courus"],
  ["277", "Actions propres ou parts propres"],
  ["2771", "Actions propres ou parts propres"],
  ["2772", "Actions propres ou parts propres en voie d'annulation"],
  ["279", "Versements restant à effectuer sur titres immobilisés non libérés"],
  ["28", "Amortissements des immobilisations"],
  ["280", "Amortissements des immobilisations incorporelles"],
  ["2801", "Frais d'établissement"],
  ["2803", "Frais de recherche et de développement"],
  ["2805", "Concessions et droits similaires, brevets, licences, logiciels, droits et valeurs similaires"],
  ["2807", "Fonds commercial"],
  ["2808", "Autres immobilisations incorporelles"],
  ["281", "Amortissements des immobilisations corporelles"],
  ["2812", "Agencements, aménagements de terrains"],
  ["2813", "Constructions"],
  ["2814", "Constructions sur sol d'autrui"],
  ["2815", "Installations techniques, matériel et outillage industriels"],
  ["2818", "Autres immobilisations corporelles"],
  ["28181", "Installations générales, agencements, aménagements divers"],
  ["28182", "Matériel de transport"],
  ["28183", "Matériel de bureau et matériel informatique"],
  ["28184", "Mobilier"],
  ["28185", "Cheptel"],
  ["28186", "Emballages récupérables"],
  ["282", "Amortissements des immobilisations mises en concession"],
  ["29", "Dépréciations des immobilisations"],
  ["290", "Dépréciations des immobilisations incorporelles"],
  ["2905", "Marques, procédés, droits et valeurs similaires"],
  ["2906", "Droit au bail"],
  ["2907", "Fonds commercial"],
  ["2908", "Autres immobilisations incorporelles"],
  ["291", "Dépréciations des immobilisations corporelles"],
  ["2911", "Terrains"],
  ["2913", "Constructions"],
  ["2915", "Installations techniques, matériel et outillage industriels"],
  ["2918", "Autres immobilisations corporelles"],
  ["292", "Dépréciations des immobilisations mises en concession"],
  ["293", "Dépréciations des immobilisations en cours"],
  ["296", "Dépréciations des participations et créances rattachées à des participations"],
  ["2961", "Titres de participation"],
  ["2966", "Autres formes de participation"],
  ["2967", "Créances rattachées à des participations"],
  ["297", "Dépréciations des autres immobilisations financières"],
  ["2971", "Titres immobilisés autres que les titres immobilisés de l'activité de portefeuille (droit de propriété)"],
  ["2972", "Titres immobilisés (droit de créance)"],
  ["2973", "Titres immobilisés de l'activité de portefeuille"],
  ["2974", "Prêts"],
  ["2975", "Dépôts et cautionnements versés"],
  ["2976", "Autres créances immobilisées"],
  // ---------- Classe 3 ----------
  ["31", "Matières premières (et fournitures)"],
  ["311", "Matières (ou groupe) A"],
  ["312", "Matières (ou groupe) B"],
  ["317", "Fournitures A, B, C, ..."],
  ["32", "Autres approvisionnements"],
  ["321", "Matières consommables"],
  ["322", "Fournitures consommables"],
  ["3221", "Combustibles"],
  ["3222", "Produits d'entretien"],
  ["3223", "Fournitures d'atelier et d'usine"],
  ["3224", "Fournitures de magasin"],
  ["3225", "Fournitures de bureau"],
  ["326", "Emballages"],
  ["3261", "Emballages perdus"],
  ["3265", "Emballages récupérables non identifiables"],
  ["3267", "Emballages à usage mixte"],
  ["33", "En-cours de production de biens"],
  ["331", "Produits en cours"],
  ["335", "Travaux en cours"],
  ["34", "En-cours de production de services"],
  ["341", "Études en cours"],
  ["345", "Prestations de services en cours"],
  ["35", "Stocks de produits"],
  ["351", "Produits intermédiaires"],
  ["355", "Produits finis"],
  ["358", "Produits résiduels (ou matières de récupération)"],
  ["3581", "Déchets"],
  ["3585", "Rebuts"],
  ["3586", "Matières de récupération"],
  ["37", "Stocks de marchandises"],
  ["371", "Marchandises (ou groupe) A"],
  ["372", "Marchandises (ou groupe) B"],
  ["39", "Dépréciations des stocks et en-cours"],
  ["391", "Dépréciations des matières premières (et fournitures)"],
  ["392", "Dépréciations des autres approvisionnements"],
  ["393", "Dépréciations des en-cours de production de biens"],
  ["394", "Dépréciations des en-cours de production de services"],
  ["395", "Dépréciations des stocks de produits"],
  ["397", "Dépréciations des stocks de marchandises"],
  // ---------- Classe 4 ----------
  ["40", "Fournisseurs et comptes rattachés"],
  ["401", "Fournisseurs"],
  ["4011", "Fournisseurs - Achats de biens ou de prestations de services"],
  ["4017", "Fournisseurs - Retenues de garantie"],
  ["403", "Fournisseurs - Effets à payer"],
  ["404", "Fournisseurs d'immobilisations"],
  ["4041", "Fournisseurs - Achats d'immobilisations"],
  ["4047", "Fournisseurs d'immobilisations - Retenues de garantie"],
  ["405", "Fournisseurs d'immobilisations - Effets à payer"],
  ["408", "Fournisseurs - Factures non parvenues"],
  ["4081", "Fournisseurs"],
  ["4084", "Fournisseurs d'immobilisations"],
  ["4088", "Fournisseurs - Intérêts courus"],
  ["409", "Fournisseurs débiteurs"],
  ["4091", "Fournisseurs - Avances et acomptes versés sur commandes"],
  ["4096", "Fournisseurs - Créances pour emballages et matériel à rendre"],
  ["4097", "Fournisseurs - Autres avoirs"],
  ["4098", "Rabais, remises, ristournes à obtenir et autres avoirs non encore reçus"],
  ["41", "Clients et comptes rattachés"],
  ["411", "Clients"],
  ["4111", "Clients - Ventes de biens ou de prestations de services"],
  ["4117", "Clients - Retenues de garantie"],
  ["413", "Clients - Effets à recevoir"],
  ["416", "Clients douteux ou litigieux"],
  ["418", "Clients - Produits non encore facturés"],
  ["4181", "Clients - Factures à établir"],
  ["4188", "Clients - Intérêts courus"],
  ["419", "Clients créditeurs"],
  ["4191", "Clients - Avances et acomptes reçus sur commandes"],
  ["4196", "Clients - Dettes sur emballages et matériel consignés"],
  ["4197", "Clients - Autres avoirs"],
  ["4198", "Rabais, remises, ristournes à accorder et autres avoirs à établir"],
  ["42", "Personnel et comptes rattachés"],
  ["421", "Personnel - Rémunérations dues"],
  ["422", "Comités d'entreprise, d'établissement, ..."],
  ["424", "Participation des salariés aux résultats"],
  ["4246", "Réserve spéciale"],
  ["4248", "Comptes courants"],
  ["425", "Personnel - Avances et acomptes"],
  ["426", "Personnel - Dépôts"],
  ["427", "Personnel - Oppositions"],
  ["428", "Personnel - Charges à payer et produits à recevoir"],
  ["4282", "Dettes provisionnées pour congés à payer"],
  ["4284", "Dettes provisionnées pour participation des salariés aux résultats"],
  ["4286", "Autres charges à payer"],
  ["4287", "Produits à recevoir"],
  ["43", "Sécurité sociale et autres organismes sociaux"],
  ["431", "Sécurité sociale"],
  ["437", "Autres organismes sociaux"],
  ["438", "Organismes sociaux - Charges à payer et produits à recevoir"],
  ["4382", "Charges sociales sur congés à payer"],
  ["4386", "Autres charges à payer"],
  ["4387", "Produits à recevoir"],
  ["44", "État et autres collectivités publiques"],
  ["441", "État - Subventions à recevoir"],
  ["4411", "Subventions d'investissement"],
  ["4417", "Subventions d'exploitation"],
  ["4418", "Subventions d'équilibre"],
  ["4419", "Avances sur subventions"],
  ["442", "État - Impôts et taxes recouvrables sur des tiers"],
  ["4424", "Obligataires"],
  ["4425", "Associés"],
  ["443", "Opérations particulières avec l'État, les collectivités publiques, les organismes internationaux"],
  ["444", "État - Impôts sur les bénéfices"],
  ["445", "État - Taxes sur le chiffre d'affaires"],
  ["4452", "TVA due intracommunautaire"],
  ["4455", "Taxes sur le chiffre d'affaires à décaisser"],
  ["44551", "TVA à décaisser"],
  ["44558", "Taxes assimilées à la TVA"],
  ["4456", "Taxes sur le chiffre d'affaires déductibles"],
  ["44562", "TVA sur immobilisations"],
  ["44563", "TVA transférée par d'autres entreprises"],
  ["44566", "TVA sur autres biens et services"],
  ["44567", "Crédit de TVA à reporter"],
  ["44568", "Taxes assimilées à la TVA"],
  ["4457", "Taxes sur le chiffre d'affaires collectées par l'entreprise"],
  ["44571", "TVA collectée"],
  ["44578", "Taxes assimilées à la TVA"],
  ["4458", "Taxes sur le chiffre d'affaires à régulariser ou en attente"],
  ["44581", "Acomptes - Régime simplifié d'imposition"],
  ["44583", "Remboursement de TVA demandé"],
  ["44584", "TVA récupérée d'avance"],
  ["44586", "TVA sur factures non parvenues"],
  ["44587", "TVA sur factures à établir"],
  ["446", "Obligations cautionnées"],
  ["447", "Autres impôts, taxes et versements assimilés"],
  ["448", "État - Charges à payer et produits à recevoir"],
  ["4482", "Charges fiscales sur congés à payer"],
  ["4486", "Charges à payer"],
  ["4487", "Produits à recevoir"],
  ["449", "Quotas d'émission à restituer à l'État"],
  ["45", "Groupe et associés"],
  ["451", "Groupe"],
  ["455", "Associés - Comptes courants"],
  ["4551", "Principal"],
  ["4558", "Intérêts courus"],
  ["456", "Associés - Opérations sur le capital"],
  ["4561", "Associés - Comptes d'apport en société"],
  ["4562", "Apporteurs - Capital appelé, non versé"],
  ["4563", "Associés - Versements reçus sur augmentation de capital"],
  ["4564", "Associés - Versements anticipés"],
  ["4566", "Actionnaires défaillants"],
  ["4567", "Associés - Capital à rembourser"],
  ["457", "Associés - Dividendes à payer"],
  ["458", "Associés - Opérations faites en commun et en GIE"],
  ["4581", "Opérations courantes"],
  ["4588", "Intérêts courus"],
  ["46", "Débiteurs divers et créditeurs divers"],
  ["462", "Créances sur cessions d'immobilisations"],
  ["464", "Dettes sur acquisitions de valeurs mobilières de placement"],
  ["465", "Créances sur cessions de valeurs mobilières de placement"],
  ["467", "Autres comptes débiteurs ou créditeurs"],
  ["468", "Divers - Charges à payer et produits à recevoir"],
  ["4686", "Charges à payer"],
  ["4687", "Produits à recevoir"],
  ["47", "Comptes transitoires ou d'attente"],
  ["471", "Comptes d'attente"],
  ["476", "Différences de conversion - Actif"],
  ["4761", "Diminution des créances"],
  ["4762", "Augmentation des dettes"],
  ["4768", "Différences compensées par couverture de change"],
  ["477", "Différences de conversion - Passif"],
  ["4771", "Augmentation des créances"],
  ["4772", "Diminution des dettes"],
  ["4778", "Différences compensées par couverture de change"],
  ["478", "Autres comptes transitoires"],
  ["4781", "Mali de fusion sur actif circulant"],
  ["48", "Comptes de régularisation"],
  ["481", "Charges à répartir sur plusieurs exercices"],
  ["4816", "Frais d'émission des emprunts"],
  ["486", "Charges constatées d'avance"],
  ["487", "Produits constatés d'avance"],
  ["488", "Comptes de répartition périodique des charges et des produits"],
  ["4886", "Charges"],
  ["4887", "Produits"],
  ["49", "Dépréciations des comptes de tiers"],
  ["491", "Dépréciations des comptes clients"],
  ["495", "Dépréciations des comptes du groupe et des associés"],
  ["4951", "Comptes du groupe"],
  ["4955", "Comptes courants des associés"],
  ["4958", "Opérations faites en commun et en GIE"],
  ["496", "Dépréciations des comptes de débiteurs divers"],
  ["4962", "Créances sur cessions d'immobilisations"],
  ["4965", "Créances sur cessions de valeurs mobilières de placement"],
  ["4967", "Autres comptes débiteurs"],
  // ---------- Classe 5 ----------
  ["50", "Valeurs mobilières de placement"],
  ["501", "Parts dans des entreprises liées"],
  ["502", "Actions propres"],
  ["503", "Actions"],
  ["5031", "Titres cotés"],
  ["5035", "Titres non cotés"],
  ["504", "Autres titres conférant un droit de propriété"],
  ["505", "Obligations et bons émis par la société et rachetés par elle"],
  ["506", "Obligations"],
  ["5061", "Titres cotés"],
  ["5065", "Titres non cotés"],
  ["507", "Bons du Trésor et bons de caisse à court terme"],
  ["508", "Autres valeurs mobilières de placement et autres créances assimilées"],
  ["5081", "Autres valeurs mobilières"],
  ["5082", "Bons de souscription"],
  ["5088", "Intérêts courus sur obligations, bons et valeurs assimilés"],
  ["509", "Versements restant à effectuer sur valeurs mobilières de placement non libérées"],
  ["51", "Banques, établissements financiers et assimilés"],
  ["511", "Valeurs à l'encaissement"],
  ["5112", "Chèques à encaisser"],
  ["5113", "Effets à l'encaissement"],
  ["5114", "Effets à l'escompte"],
  ["512", "Banques"],
  ["5121", "Comptes en monnaie nationale"],
  ["5124", "Comptes en devises"],
  ["514", "Chèques postaux"],
  ["515", "Caisses du Trésor et des établissements publics"],
  ["516", "Sociétés de bourse"],
  ["517", "Autres organismes financiers"],
  ["518", "Intérêts courus"],
  ["5181", "Intérêts courus à payer"],
  ["5188", "Intérêts courus à recevoir"],
  ["519", "Concours bancaires courants"],
  ["5191", "Crédit de mobilisation de créances commerciales (CMCC)"],
  ["5193", "Mobilisation de créances nées à l'étranger"],
  ["5198", "Intérêts courus sur concours bancaires courants"],
  ["52", "Instruments financiers à terme et jetons détenus"],
  ["521", "Instruments financiers à terme"],
  ["522", "Jetons détenus"],
  ["53", "Caisse"],
  ["531", "Caisse siège social"],
  ["5311", "Caisse en monnaie nationale"],
  ["5314", "Caisse en devises"],
  ["532", "Caisse succursale (ou usine) A"],
  ["533", "Caisse succursale (ou usine) B"],
  ["54", "Régies d'avances et accréditifs"],
  ["58", "Virements internes"],
  ["59", "Dépréciations des comptes financiers"],
  ["590", "Dépréciations des valeurs mobilières de placement"],
  ["5903", "Actions"],
  ["5904", "Autres titres conférant un droit de propriété"],
  ["5906", "Obligations"],
  ["5908", "Autres valeurs mobilières de placement et créances assimilées"]
];
